package br.udesc.exemplomarcarconsulta.visao;

import br.udesc.exemplomarcarconsulta.dao.ConsultaListDAO;
import br.udesc.exemplomarcarconsulta.modelo.Consulta;
import br.udesc.exemplomarcarconsulta.repositorio.ConsultaRepositorio;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

/**
 *
 * @author mattheus
 */
public class TelaVisualizarConsultas extends javax.swing.JFrame {

    /**
     * Creates new form TelaVisualizarConsultas
     */
    public TelaVisualizarConsultas() {
        initComponents();
        preencherConsultas(getConsultas());
        
        btnOrdenarDataCrescente.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ordenarConsultasDataCrescente();
            }
        });
        
        btnOrdenarDataDecrescente.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ordenarConsultasDataDecrescente();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsultas = new javax.swing.JTextArea();
        btnOrdenarDataCrescente = new javax.swing.JButton();
        btnOrdenarDataDecrescente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtConsultas.setEditable(false);
        txtConsultas.setColumns(20);
        txtConsultas.setRows(5);
        jScrollPane1.setViewportView(txtConsultas);

        btnOrdenarDataCrescente.setText("Ordem crescente por data");

        btnOrdenarDataDecrescente.setText("Ordem decrescente por data ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOrdenarDataCrescente, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOrdenarDataDecrescente, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenarDataCrescente)
                    .addComponent(btnOrdenarDataDecrescente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public List<Consulta> getConsultas() {
        ConsultaRepositorio consultaRepositorio = new ConsultaListDAO();
        List<Consulta> consultas = consultaRepositorio.recuperarTodosConsultas();
        return consultas;
    }

    public void preencherConsultas(List<Consulta> consultas) {
        limparConsultas();
        for (Consulta c : consultas) {
            txtConsultas.append(c.toString());
            txtConsultas.append("\n");
        }
    }

    public void ordenarConsultasDataCrescente() {
        List<Consulta> consultas = getConsultas();
        Collections.sort(consultas);
        preencherConsultas(consultas);
    }

    public void ordenarConsultasDataDecrescente() {
        List<Consulta> consultas = getConsultas();
        Collections.sort(consultas, new Comparator<Consulta>() {
            @Override
            public int compare(Consulta c1, Consulta c2) {
                if (c1.getDataHora().isAfter(c2.getDataHora())) {
                    return -1;
                } else {
                    return 1;
                }
            }
        });
        preencherConsultas(consultas);
    }

    public void limparConsultas() {
        txtConsultas.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVisualizarConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVisualizarConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrdenarDataCrescente;
    private javax.swing.JButton btnOrdenarDataDecrescente;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtConsultas;
    // End of variables declaration//GEN-END:variables
}
